name: sberswap
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cython
  - matplotlib
  - ipykernel
  - numpy=1.23
  - pip:
    - opencv-python==4.1.2.30
    - kornia==0.6
    - insightface==0.2.1
    - onnxruntime
    - dill
    - scikit-image
    - wandb
